const express = require("express");
const pages = require("../controllers/htmlController");
const loginController = require("../controllers/loginController");
const middle = require("../controllers/middleController");
const router = express.Router();

router.route("/").get(middle.redirectSignin, pages.profile);
router.route("/signin").get(middle.redirectProfile, pages.signin);
router.route("/signup").get(middle.redirectProfile, pages.signup);
router.route("/signin_otp").get(pages.signin_otp);
router.route("/dentistry").get(pages.dentistry);
router.route("/about_hospital").get(pages.about_hospital);
router.route("/aboutus").get(pages.aboutus);
router.route("/appointment").get(pages.appointment);
router.route("/contactus").get(pages.contactus);
router.route("/doctor").get(pages.doctor);
router.route("/doctors_profile").get(pages.doctors_profile);
router.route("/faq").get(pages.faq);
router.route("/hospital").get(pages.hospital);
router.route("/index").get(pages.index);
router.route("/reset_password").get(pages.reset_password);
router.route("/otps").get(pages.otps);
router.route("/passOtp").get(pages.passOtp);
router.route("/tvastra_plus").get(pages.tvastra_plus);
router.route("/complete_profile").get(pages.complete_profile);
router.route("/dashboard").get(pages.dashboard);
router.route("/editProfile").get(pages.editProfile);
router.route("/editSchedule").get(pages.editSchedule);
router.route("/scheduleDone").get(pages.scheduleDone);
router.route("/medicalReport").get(pages.medicalReport);
router.route("/record").get(pages.record);
router.route("/setting").get(pages.setting);
router.route("/otp/:token").post(loginController.signin_otp);
router.route("/otps").post(loginController.otps);
router.route("/signin").post(loginController.signin);
router.route("/signup").post(loginController.signup);
router.route("/signOut").post(loginController.signOut);
router.route("/forgotPass/:token").post(loginController.forgotPass);
router.route("/resetPass").post(loginController.resetPass);
router.route("/changePass").post(loginController.changePass);
router.route("/complete_profile").post(loginController.complete_profile);
router.route("/dashboard").post(loginController.dashboard);
router.route("/dashboard").post(loginController.dashboard);
router.route("/editProfile").post(loginController.editProfile);
router.route("/editSchedule").post(loginController.editSchedule);
router.route("/medicalReport").post(loginController.medicalReport);
router.route("/setting").post(loginController.setting);
router.route("/changeProfile").post(loginController.changeProfile);
router.route("/createSchedule").post(loginController.createSchedule);
router.route("/viewSlots").post(loginController.viewSlots);
router.route("/rmvSlot").post(loginController.rmvSlot);
router.route("/scheduleDone").post(loginController.scheduleDone);
router.route("/scheduleSlotDone").post(loginController.scheduleSlotDone);
router.route("/addRecords").post(loginController.addRecords);
router.route("/rmvRecord").post(loginController.rmvRecord);
router.route("/record").post(loginController.record);
router.route("/newRecord").post(loginController.newRecord);
router.route("/deleteReportImg").post(loginController.deleteReportImg);
router.route("/settingPassword").post(loginController.settingPassword);
router.route("/doctorInfo").post(loginController.doctorInfo);

module.exports = router;