const express = require("express");
const pages = require("../controllers/htmlController");
const loginController = require("../controllers/loginController");
const middle = require("../controllers/middleController");
const router = express.Router();

router.route("/").get(middle.redirectSignin, pages.profile);
router.route("/signin").get(middle.redirectProfile, pages.signin);
router.route("/signup").get(middle.redirectProfile, pages.signup);
router.route("/signin_otp").get(pages.signin_otp);
router.route("/dentistry").get(pages.dentistry);
router.route("/about_hospital").get(pages.about_hospital);
router.route("/aboutus").get(pages.aboutus);
router.route("/appointment").get(pages.appointment);
router.route("/contactus").get(pages.contactus);
router.route("/doctor").get(pages.doctor);
router.route("/doctors_profile").get(pages.doctors_profile);
router.route("/faq").get(pages.faq);
router.route("/hospital").get(pages.hospital);
router.route("/index").get(pages.index);
router.route("/reset_password").get(pages.reset_password);
router.route("/otps").get(pages.otps);
router.route("/passOtp").get(pages.passOtp);
router.route("/tvastra_plus").get(pages.tvastra_plus);
router.route("/otp/:token").post(loginController.signin_otp);
router.route("/otps").post(loginController.otps);
router.route("/signin").post(loginController.signin);
router.route("/signup").post(loginController.signup);
router.route("/signOut").post(loginController.signOut);
router.route("/forgotPass/:token").post(loginController.forgotPass);
router.route("/resetPass").post(loginController.resetPass);
router.route("/changePass").post(loginController.changePass);

module.exports = router;